### PR TITLE
MQTT and Charts updated

### PR DESCRIPTION
**Pull request by antonio-openroad**
Fix crash when using MQTT (updated MQTT library)
Updated charts library
Fix flickering row in 'Modules' screen when running from macOS

### CODE REVIEW

**Review by tannewt — COMMENTED** [review]
Do you need to check in the Pods? They add a lot of files to the PR.

**Comment by antonio-openroad** [comment]
> Do you need to check in the Pods? They add a lot of files to the PR.

We could ignore them and install them before building the app and we repo will be smaller, but It is recommended to check them to avoid any problems with minor updates to the Pods changing the behaviour of the app.

The official documentation of CocoaPods also recommends it:
https://guides.cocoapods.org/using/using-cocoapods.html

```
Should I check the Pods directory into source control?
Whether or not you check in your Pods folder is up to you, as workflows vary from project to project. We recommend that you keep the Pods directory under source control, and don't add it to your .gitignore. But ultimately this decision is up to you
```

There are good arguments on both sides anyway...

**Comment by tannewt** [comment]
My preference would be to rely on `Podfile.lock` to install the correct versions. Checking them in causes a bunch of noise in the PRs and I already have trouble knowing what to review.

**Comment by antonio-openroad** [comment]
> My preference would be to rely on `Podfile.lock` to install the correct versions. Checking them in causes a bunch of noise in the PRs and I already have trouble knowing what to review.

Ok. I have removed the Pods directory from source control and added a new step to the GitHub Action to execute 'pod install'

**Pull request merged**
