### PR TITLE
Migration to Swift_4

### PR DESCRIPTION
**Pull request by Booharin**
Hello, this version of Bluefruit_LE_Connect_v2 for Swift 4.

### CODE REVIEW

**Comment by Eashir** [comment]
Hey! Sorry to bother you, but can you give a rough estimate of how long it might take for Swift 4?

**Comment by Booharin** [comment]
Hello! It's ok! This project took me a week of time.

**Comment by Eashir** [comment]
Nice, and when will we be able to use it :3

**Comment by Booharin** [comment]
Сurrently working on the bugs, will soon earn:)

**Comment by Eashir** [comment]
Awesome, thank you Booharin!

**Comment by Booharin** [comment]
Eashir, no truble!:)

**Comment by microbuilder** [comment]
Sorry, we did some reorg to make the swift3 branch the default, and removed 'master' and that seems to have closed this.

**Comment by antonio-openroad** [comment]
@Booharin thanks for taking the time to submit this code. 
There are 2 main problems to accept your pull request:
- It seems that you used  the old swift2 codebase and not the newer swift3 branch that is very different. The master branch now contains the latest code.
- Its better if you submit small changes so they can be discussed before being added. This pull request affects more than 400 files, it's not easy to check and discuss the changes.

You are more than welcome to submit pull request if you find any bugs

**Comment by Booharin** [comment]
@antonio-openroad Thank you! It was interesting to work on your project! The next time I work with a new master branch, I'll send you a smaller submit:)

**Pull request closed without merging**
